### PR TITLE
Fix missing detail when DCD provide full type

### PR DESCRIPTION
**Pull request by RUSShyTwo**

### CODE REVIEW

**Comment by WebFreak001** [comment]
do you have an example when this happens? I would like to add a unittest & changelog entry for this

**Comment by RUSShyTwo** [comment]
Ah actually it's not needed, it was due to a change i made on my local DCD fork, but that's probably not thing that should be supported right now since it's not finish

**Comment by RUSShyTwo** [comment]
It's to support pointers:

image

in latest DCD it doesn't display the STAR

**Comment by RUSShyTwo** [comment]
it needs changes in dsymbol and dcd

**Pull request closed without merging**
