### PR TITLE
Prevent serve-d to consume 100% cpu whenever vscode is closed

### PR DESCRIPTION
**Pull request by ryuukk**
This at least doesn't make serve-d to consume 100% of the cpu..

It still doesn't close.. but at least it doesn't cause too much problems..

But since this doesn't consume 100% cpu after this change, this might be an indication on why process doesn't close, what ever thread is calling that method is stuck! that needs to be investigated!

### CODE REVIEW

**Comment by ryuukk** [comment]
what do you think?

**Comment by WebFreak001** [comment]
I will check this out later. Is everything in this PR needed? On a first glance I would think just a `break;` in the error branch would be about the same as this - though I think the errors occurred randomly before. Need to check if they happen with stuff like suspend or power save features - and if that error does get logged, need to attempt to do recovery instead of breaking the main loop. (closing the program)

**Comment by ryuukk** [comment]
> I will check this out later. Is everything in this PR needed? On a first glance I would think just a `break;` in the error branch would be about the same as this - though I think the errors occurred randomly before. Need to check if they happen with stuff like suspend or power save features - and if that error does get logged, need to attempt to do recovery instead of breaking the main loop. (closing the program)

You are right, it would be better to do recovery instead, but i'm not exactly sure how to do that, the main motivation for this PR was to eliminate the 100% CPU usage when the process is stuck..

The investigation as to why the process doesn't close is a different story.. i think that involves the code in workspace-d, but i am not really sure.. i don't have a lot of time sadly to dedicate in to this

**Comment by WebFreak001** [comment]
merged in, did not include the Thread.sleep because select already sleeps in case of no error and all error cases are now properly handled.

**Pull request closed without merging**
