### PR TITLE
Improve windows build script

### PR DESCRIPTION
**Pull request by 0xEAB**
- Get rid of locale-dependent commands
- Change build dir and make it relative to %windir%
- Sync build dir instead of delete+copy
- Move output zip instead of copying it

Works fine here :smile: 
...but test & review it, please.

### CODE REVIEW

**Comment by WebFreak001** [comment]
can you also add `dub upgrade` to the script?

**Comment by 0xEAB** [comment]
Done :)

By the way: Is there a reason why this doesn't specify `--build=release` like the bash script does?

**Comment by WebFreak001** [comment]
windows release builds always seem broken

**Comment by 0xEAB** [comment]
ah I see...

**Pull request merged**
