### PR TITLE
Implement Completion Item Label

### PR DESCRIPTION
**Pull request by RUSshy**
Looks better:

image

--

Please do not edit the PR, it was hard to edit changes again since you committed on my branch

I added changes to handle cases where function is templated

If you want to make edit, please take this PR changes and create your own PR

I will not work on this further, so if you don't want to merge, feel free to use this as a base

the code i share is PUBLIC DOMAIN

If PR not merged/closed in 1 month, i will start a FORKED extension and close this PR myself

### CODE REVIEW

**Comment by RUSshy** [comment]
image

**Comment by WebFreak001** [comment]
I edited your PR because I couldn't use your changes as-is. It would have been nice if you could have done your improvements upon my changes.

However it seems like the changes are not necessary because they were handled by my changes already.

Additionally I told you before that the change of the `label` field to a `CompletionItemLabel` struct was a no-go because it's not supported by LSP, but the way how I edited your changes is.

I appreciate the PR, however I will go with the previous PR with my changes applied instead of this one because otherwise it would break API compatibility for serve-d:lsp library users, break the LSP implementation itself (and thus all editors except vscode) and also the changes use proper parsing instead of string indexOf operations to find template syntax, etc.

**Comment by WebFreak001** [comment]
I have reopened your previous PR in #160 which includes my fixes to make it compatible with my previous review. Thanks for the work on this, has been merged in there!

**Comment by RUSshy** [comment]
thanks!

**Pull request closed without merging**
