### PR TITLE
Improve completion sorting rule

### PR DESCRIPTION
**Pull request by RUSshy**
**BEFORE:** 

image

**AFTER:**

image

### CODE REVIEW

**Comment by WebFreak001** [comment]
how does this affect completion on global scopes e.g. with `import std;` trying to complete after `w`?

**Comment by RUSshy** [comment]
Seems unchanged for importing modules 

image

For global scope seems fine too

image

image

**Comment by WebFreak001** [comment]
the changes where all of these are put now mean that the snippet prefix needs to be updated

**Comment by RUSshy** [comment]
Good catch, done!

**Comment by RUSshy** [comment]
I've been using this setup for few minutes and it is SO MUCH BETTER

I know right at first sight what things are, and where to put my cursor, feels cleaner

**Comment by WebFreak001** [comment]
well let's put it in and see what nightly users are gonna think (if anything)

**Comment by WebFreak001** [comment]
for further improvements please submit here what you expect it to look like: https://completion.webfreak.org/

**Comment by RUSshy** [comment]
@WebFreak001 great idea, you should post it on the forum/discord aswel to get more data

**Comment by WebFreak001** [comment]
so far out of the first 10 responses 8 were customized and show a general trend, nearly all responses have grouped similar things together: https://completion.webfreak.org/view.html

**Pull request merged**
