### PR TITLE
Use skipOver in uriToFile

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by WebFreak001** [comment]
the return variable ret has been removed, also the decodeComponent part on the remainder of the URL (which in hindsight might not be the optimal place, but idk if there are tests for it why I added it in the first place)

**Comment by nordlow** [comment]
> the return variable ret has been removed, also the decodeComponent part on the remainder of the URL (which in hindsight might not be the optimal place, but idk if there are tests for it why I added it in the first place)

Fixed.

**Comment by nordlow** [comment]
Failure in 

```
Run Unittests / Dub Tests (macos-latest, ldc-latest) (pull_request) Failing after 3m 
```

seems unrelated. Am stuck.

**Comment by nordlow** [comment]
Ping, @WebFreak001.

**Review by WebFreak001 — APPROVED** [review]

**Pull request merged**
